### ISSUE TITLE
chaincode package error 

### ISSUE THREAD

**Issue by Shishircipher** [awsdocs/amazon-managed-blockchain-hyperledger-fabric-developer-guide#3]
when i am using this command - `docker exec cli peer lifecycle chaincode package ./abstore.tar.gz --path fabric-samples/chaincode/abstore/go/ --label abstore_1`, this give me following error - `Error: failed to normalize chaincode path: 'go list' failed with: error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping.: exit status 1`

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
